GODOT=Godot_v4.3-stable_mono_win64.exe
ISCC=ISCC.exe
ZIP=7z.exe

BIN_DIR=Bin
WIN_DEBUG_DIR=$(BIN_DIR)\WinDebug
WIN_RELEASE_DIR=$(BIN_DIR)\WinRelease
LINUX_RELEASE_DIR=$(BIN_DIR)\LinuxRelease
MACOS_RELEASE_DIR=$(BIN_DIR)\MacOSRelease
ASSETS_DIR=Assets

GAME_DIR=..\Game
APP_NAME=Asteroids
ASTEROIDS_EXE=Asteroids.exe

VERSION=1.0.0